CREATE DATABASE DB_P2
CHARACTER SET utf8
COLLATE utf8_general_ci;

USE DB_P2;

CREATE TABLE PACIENTE (
	idPaciente INT,
    edad INT,
    genero VARCHAR(20),
    CONSTRAINT pk_paciente PRIMARY KEY(idPaciente)
);

CREATE TABLE HABITACION (
	idHabitacion INT,
    habitacion VARCHAR(50),
    CONSTRAINT pk_habitacion PRIMARY KEY (idHabitacion)
);

CREATE TABLE LOG_HABITACION (
	id_log_habitacion INT AUTO_INCREMENT,
	timestampx VARCHAR(100),
    statusx VARCHAR(45),
    idHabitacion INT,
    Habitacion VARCHAR(100),
    CONSTRAINT pk_loghabitacion PRIMARY KEY (id_log_habitacion),
    CONSTRAINT fk_habitacionlog FOREIGN KEY (idHabitacion) REFERENCES HABITACION(idHabitacion)
);



CREATE TABLE LOG_ACTIVIDAD (
	id_log_actividad INT AUTO_INCREMENT,
    timestampx VARCHAR(100),
    actividad VARCHAR(500),
    idPaciente INT,
    idHabitacion INT,
    CONSTRAINT pk_logactividad PRIMARY KEY (id_log_actividad),
    CONSTRAINT fk_pacienteactividad FOREIGN KEY (idPaciente) REFERENCES PACIENTE(idPaciente),
    CONSTRAINT fk_habitacionactividad FOREIGN KEY (idHabitacion) REFERENCES HABITACION(idHabitacion)
);

LOAD DATA
INFILE 'C:\\CSVInputFiles\\Habitaciones.csv'
INTO TABLE HABITACION
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA
INFILE 'C:\\CSVInputFiles\\Pacientes.csv'
INTO TABLE PACIENTE
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA
INFILE 'C:\\CSVInputFiles\\LogHabitaciones.csv'
IGNORE
INTO TABLE LOG_HABITACION
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(idHabitacion,timestampx,statusx,Habitacion);

LOAD DATA
INFILE 'C:\\CSVInputFiles\\Logactividades1.csv'
IGNORE
INTO TABLE LOG_ACTIVIDAD
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(timestampx,actividad,idHabitacion,idPaciente);

LOAD DATA
INFILE 'C:\\CSVInputFiles\\LogActividades2.csv'
IGNORE
INTO TABLE LOG_ACTIVIDAD
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(timestampx,actividad,idHabitacion,idPaciente);



SELECT * FROM PACIENTE LIMIT 20;
SELECT * FROM HABITACION LIMIT 20;
SELECT * FROM LOG_HABITACION LIMIT 20;
SELECT * FROM LOG_ACTIVIDAD LIMIT 20;

SELECT COUNT(*) FROM PACIENTE;
SELECT COUNT(*) FROM HABITACION;
SELECT COUNT(*) FROM LOG_HABITACION;
SELECT COUNT(*) FROM LOG_ACTIVIDAD;

SELECT * FROM PACIENTE ORDER BY 1 DESC LIMIT 20;
SELECT * FROM HABITACION ORDER BY 1 DESC LIMIT 20;
SELECT * FROM LOG_HABITACION ORDER BY 1 DESC LIMIT 20;
SELECT * FROM LOG_ACTIVIDAD ORDER BY 1 DESC LIMIT 20;


